import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'realm-green': '#4EC44E',
        'realm-dark': '#1A3D1A',
        'realm-shadow': '#2B6B2B',
        'realm-black': '#111811',
        "on-primary": "#ffffff",
        "surface-container-highest": "#1c1c1c",
        "on-secondary-fixed": "#002204",
        "inverse-primary": "#69df65",
        "on-tertiary-fixed-variant": "#0e5215",
        "surface-bright": "#1c1c1c",
        "on-error": "#ffffff",
        "outline-variant": "#3e4a3b",
        "secondary": "#43673f",
        "surface-container-lowest": "#0a0a0a",
        "tertiary-container": "#7abd73",
        "secondary-fixed": "#c4eebb",
        "tertiary": "#2b6b2b",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "primary": "#4EC44E",
        "error": "#ba1a1a",
        "primary-fixed": "#85fc7e",
        "surface-container-high": "#2c2c2c",
        "secondary-container": "#c4eebb",
        "on-surface": "#fcf9f8",
        "outline": "#6e7b69",
        "surface-container-low": "#161616",
        "primary-fixed-dim": "#69df65",
        "surface": "#121212",
        "inverse-on-surface": "#1c1b1b",
        "on-primary-container": "#e8f5e9",
        "on-surface-variant": "#aebbb0",
        "on-primary-fixed-variant": "#00530d",
        "primary-container": "#1a3d1a",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#2b4f2a",
        "on-tertiary-fixed": "#002203",
        "on-tertiary-container": "#054c0f",
        "background": "#050805",
        "on-primary-fixed": "#002202",
        "tertiary-fixed": "#aef4a4",
        "on-background": "#fcf9f8",
        "surface-dim": "#121212",
        "surface-variant": "#1c1c1c",
        "surface-tint": "#4EC44E",
        "on-secondary-container": "#c4eebb",
        "secondary-fixed-dim": "#a8d1a1",
        "surface-container": "#1c1c1c",
        "inverse-surface": "#fcf9f8",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#92d78a"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "pixel": ["'Press Start 2P'", "monospace"]
      }
    },
  },
  plugins: [],
} satisfies Config
